### PR TITLE
feat: base ui setup and landing page

### PR DESCRIPTION
**Pull request by masterrom**
Styling Used: https://materializecss.com/

Aragon UI didn't have good documentation for styling so ended up using the materializes UI. Either way both are in the package-lock.json. Additionally, the `Connect` library is also installed.

### CODE REVIEW

**Comment by ttymarucr** [comment]
wondering if we can only use react hooks instead of complex redux reducers. I know react hooks are easier to integrate

**Comment by darknightdev** [comment]
> wondering if we can only use react hooks instead of complex redux reducers. I know react hooks are easier to integrate

Yeah I'm also thinking to use simple web3 integrations instead of Moralis connections especially when we are using Forked local network

**Comment by masterrom** [comment]
> wondering if we can only use react hooks instead of complex redux reducers. I know react hooks are easier to integrate

I added redux so it easier to manage user data. Also it was quite easy to make the setup. Can still use hooks on top of redux

**Comment by masterrom** [comment]
> > wondering if we can only use react hooks instead of complex redux reducers. I know react hooks are easier to integrate
> 
> Yeah I'm also thinking to use simple web3 integrations instead of Moralis connections especially when we are using Forked local network

We wont be eligible with for the moralis prize. But we can grab the web3 instance through moralis as well. Check this out: https://docs.moralis.io/moralis-server/web3/web3

**Review by ttymarucr — APPROVED** [review]

**Pull request merged**
